Update patch set 5
Patch Set 5: -Presubmit-Ready

It's failing again, but I know what's wrong now. The build process for the wrapper is invoking a raw "go" command. this needs to be passed the hermetic path instead.

prebuilts/go/linux-x86/bin/go (and the darwin-x86 variant) are the 2 that should be getting used here. Tobias, can you try to create the proper patch here? I can help with testing/verification (although don't forget to unhook my logging CL to test it too).

...
OSError: [Errno 2] No such file or directory
...

Patch-set: 5
Reviewer: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0