Update patch set 1
Patch Set 1:

This seems to be failing to build now. There is a conflict with what is in the bionic headers as well.

FAILED: /usr/local/google/buildbot/src/android/llvm-toolchain/out/stage2-install/bin/clang++  --sysroot=/usr/local/google/buildbot/src/android/llvm-toolchain/out/sysroots/platform/arm    --target=arm-linux-android -B/usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -D__ANDROID_API__=26 -ffunction-sections -fdata-sections -march=armv7-a -isystem /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1 -isystem /usr/local/google/buildbot/src/android/llvm-toolchain/bionic/libc/include -Wall -std=c++11 -Wno-unused-parameter    --target=arm-linux-android -B/usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -D__ANDROID_API__=26 -ffunction-sections -fdata-sections -march=armv7-a -isystem /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1 -isystem /usr/local/google/buildbot/src/android/llvm-toolchain/bionic/libc/include -Wall -std=c++11 -Wno-unused-parameter -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fno-omit-frame-pointer -MD -MT lib/fuzzer/CMakeFiles/RTfuzzer.arm.dir/FuzzerMerge.cpp.o -MF lib/fuzzer/CMakeFiles/RTfuzzer.arm.dir/FuzzerMerge.cpp.o.d -o lib/fuzzer/CMakeFiles/RTfuzzer.arm.dir/FuzzerMerge.cpp.o -c /usr/local/google/buildbot/src/android/llvm-toolchain/toolchain/compiler-rt/lib/fuzzer/FuzzerMerge.cpp
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/toolchain/compiler-rt/lib/fuzzer/FuzzerMerge.cpp:12:
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/toolchain/compiler-rt/lib/fuzzer/FuzzerCommand.h:20:
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1/sstream:174:
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1/ostream:138:
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1/ios:216:
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1/__locale:27:
In file included from /usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1/support/android/locale_bionic.h:31:
/usr/local/google/buildbot/src/android/llvm-toolchain/prebuilts/clang/host/linux-x86/clang-r339409b/include/c++/v1/support/xlocale/__posix_l_fallback.h:23:38: error: 'internal_linkage' attribute does not appear on the first declaration of 'isalnum_l'
inline _LIBCPP_INLINE_VISIBILITY int isalnum_l(int c, locale_t) {
                                     ^
/usr/local/google/buildbot/src/android/llvm-toolchain/bionic/libc/include/ctype.h:129:5: note: previous definition is here
int isalnum_l(int __ch, locale_t __l) __INTRODUCED_IN(21);
    ^

Patch-set: 1
Reviewer: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>