Update patch set 3
Patch Set 3: Code-Review-1

RuntimeError: Did not find remote_toolchain_inputs in /usr/local/google/buildbot/src/android/llvm-toolchain/out/install/linux-x86/clang-P12053082/bin

You need to pull the logic of creating remote_toolchain_inputs above this new set of lines.

Patch-set: 3
Reviewer: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=-1