Update patch set 1
Patch Set 1:

This failed to build when cherry-picked on my Mac.

[4657/4715] Building CXX object lib/fuzzer/CMakeFiles/RTfuzzer.iossim.dir/FuzzerTracePC.cpp.o
FAILED: /Volumes/Android/srhines/llvm-toolchain/out/stage2/./bin/clang++     -Wall -std=c++11 -Wno-unused-parameter -O3 -DNDEBUG -arch i386 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk    -stdlib=libc++ -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk -fPIC -fno-builtin -fno-exceptions -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fno-omit-frame-pointer -MD -MT lib/fuzzer/CMakeFiles/RTfuzzer.iossim.dir/FuzzerTracePC.cpp.o -MF lib/fuzzer/CMakeFiles/RTfuzzer.iossim.dir/FuzzerTracePC.cpp.o.d -o lib/fuzzer/CMakeFiles/RTfuzzer.iossim.dir/FuzzerTracePC.cpp.o -c /Volumes/Android/srhines/llvm-toolchain/toolchain/llvm/projects/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp
/Volumes/Android/srhines/llvm-toolchain/toolchain/llvm/projects/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp:27:1: error: thread-local storage is not supported for the current target
ATTRIBUTES_INTERFACE_TLS_INITIAL_EXEC uintptr_t __sancov_lowest_stack;
^
/Volumes/Android/srhines/llvm-toolchain/toolchain/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDefs.h:140:66: note: expanded from macro 'ATTRIBUTES_INTERFACE_TLS_INITIAL_EXEC'
  ATTRIBUTE_INTERFACE __attribute__((tls_model("initial-exec"))) thread_local
                                                                 ^
/Volumes/Android/srhines/llvm-toolchain/toolchain/llvm/projects/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp:27:1: error: 'tls_model' attribute only applies to thread-local variables
/Volumes/Android/srhines/llvm-toolchain/toolchain/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDefs.h:140:38: note: expanded from macro 'ATTRIBUTES_INTERFACE_TLS_INITIAL_EXEC'
  ATTRIBUTE_INTERFACE __attribute__((tls_model("initial-exec"))) thread_local
                                     ^
2 errors generated.
[4657/4715] Building CXX object lib/asan/CMakeFiles/RTAsan_dynamic.ios.dir/asan_interceptors.cc.o
ninja: build stopped: subcommand failed.
FAILED: cd /Volumes/Android/srhines/llvm-toolchain/out/stage2/tools/clang/runtime/compiler-rt-bins && /Volumes/Android/srhines/llvm-toolchain/prebuilts/cmake/darwin-x86/bin/cmake --build . && /Volumes/Android/srhines/llvm-toolchain/prebuilts/cmake/darwin-x86/bin/cmake -E touch /Volumes/Android/srhines/llvm-toolchain/out/stage2/tools/clang/runtime/compiler-rt-stamps//compiler-rt-build
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./build.py", line 1777, in <module>
    main()
  File "./build.py", line 1716, in main
    args.debug, args.no_lto, instrumented, profdata)
  File "./build.py", line 1303, in build_stage2
    extra_env=stage2_extra_env)
  File "./build.py", line 823, in build_llvm
    cmake_path=utils.llvm_path())
  File "./build.py", line 366, in invoke_cmake
    check_call([ninja_bin_path()] + ninja_target, cwd=out_path, env=env)
  File "./build.py", line 57, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Volumes/Android/srhines/llvm-toolchain/prebuilts/cmake/darwin-x86/bin/ninja']' returned non-zero exit status 1

Patch-set: 1
Reviewer: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0